version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - USER
      - PASSWORD

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend